server:
  port: 8189
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
spring:
  flyway:
    user: sa
    password:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1
  main:
    allow-circular-references: true
  datasource:
    generate-unique-name: false
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:chat-app
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
