server:
  port: 8189
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
spring:
  datasource:
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./users;MODE=PostgreSQL
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: false
      enabled: true
